# -*- coding: utf-8 -*-
"""automate_KellogMK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oh7dNG3rI0BtEY6hRMdeewUwSWXcOnrO
"""

import os
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def run_automation():
    # 1. Ambil data mentah
    df = pd.read_csv("loan_dataset_raw/loan_approval_dataset.csv")

    # 2. Proses Pembersihan
    df.columns = df.columns.str.strip()

    categorical_cols = df.select_dtypes(include=['object']).columns
    for col in categorical_cols:
        df[col] = df[col].str.strip()

    if 'loan_id' in df.columns:
        df = df.drop(columns=['loan_id'])

    le = LabelEncoder()
    for col in ['education', 'self_employed', 'loan_status']:
        df[col] = le.fit_transform(df[col])

    # --- PERBAIKAN DI SINI ---
    # Membuat folder tujuan secara otomatis jika belum ada di server
    output_dir = "preprocessing/loan_dataset_preprocessing"
    os.makedirs(output_dir, exist_ok=True)
    # -------------------------

    # 3. Simpan hasil ke folder khusus
    df.to_csv(f"{output_dir}/loan_clean.csv", index=False)
    print("Preprocessing Berhasil! Data siap dilatih.")

if __name__ == "__main__":
    run_automation()